### ISSUE TITLE
2024 年的《回国休假记》出现了《回国休假记（下）》的评论

### ISSUE THREAD

**Issue by CyrusYip** [yufree/yufree.cn#452]
https://yufree.cn/cn/2024/02/21/vacation/

![image](https://github.com/yufree/yufree.cn/assets/60951091/57c15bca-2402-4ac5-9223-b8e2fabc9bb7)

**Comment by yufree** [comment]
额，这是giscus的设置问题，我之前文章没出现过重名的，现在看似乎giscus对括号等特殊符号进行了忽略，导致重名了。不过也好，那篇恰好是我上次回家过年写的，隔了六年有个呼应也好。

**Comment by CyrusYip** [comment]
https://github.com/yufree/hugo-lithium-theme/blob/14f607a7296e4936fdce4e3a71932a41fbd82d74/layouts/partials/giscus.html#L6

原来你设置的 mapping 是 title，那改了标题岂不是评论会乱。感觉设置为 pathname 会比较稳妥。不过你有那么多评论了，还是别改啦。
